spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermercado_estoque?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

##logging:
  #level:
  #  gabrieldev.com.supermercado_estoque: INFO
 # pattern:
 #   console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"